pin `seaborn` version to 0.11.2 or less
rs-station/rs-booster pull request #37
Opened 2023-02-10 21:50 UTC by dennisbrookner

Pinning seaborn version to `0.11.2` because `0.12.0` or greater breaks plotting functionality for reasons currently unknown.

This PR probably should not be merged until we have an actual understanding of what has changed!

2023-03-29 16:29 UTC, dennisbrookner commented
Just realized that this was never merged; I think as per the discussion in the issue linked above, just pinning the `seaborn` version is the best call.

2023-03-30 01:36 UTC, JBGreisman commented on setup.py
> +                      "seaborn==0.11.2"
Let's make this "<=" -- I don't think this needs to be pinned to a specific version

2023-03-30 01:37 UTC, JBGreisman requested changes
This is fine. I think we should update the code so that it works with the latest `seaborn`, but this is fine to avoid issues until we do so.

2023-07-31 20:29 UTC, kmdalton commented
apparently, @DHekstra  has worked around this by explicitly coercing dtypes in the affected scripts. closing.

2023-07-31 20:29 UTC, closed without merging

2023-07-31 20:56 UTC, DHekstra commented
yes, that was just a side effect :)